version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ovs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: votingsys
    ports:
      - "3306:3306"
    volumes:
      - ./setup_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
